# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0b6ffdf911d62c24566813f8e2b636db"
name = "complyguard-ai"
application_url = "https://api.shopiters.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app_subscriptions_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_legal_policies,read_script_tags,read_themes,write_legal_policies,write_products"

[auth]
redirect_urls = [
  "https://api.shopiters.com/auth/callback",
  "https://api.shopiters.com/auth/shopify/callback",
  "https://api.shopiters.com/api/auth/callback"
]
